name: 'Cypress Integration Tests'

on: [push]

jobs:
  cypressIntegration:
    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017

    runs-on: ubuntu-latest
    steps:
      # Checkout each the UI and R5 into separate subdirectories
      - uses: actions/checkout@v3
        with:
          repository: conveyal/analysis-ui
          ref: 1701bd9aea859a4714bc3f35f5bcf767a3256a64
          fetch-depth: 0
          path: ui
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: r5
      # Build R5 and check that it can start up as a backend
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 19
          cache: gradle
      - run: |
          cp analysis.properties.template analysis.properties
          gradle testRunnable -x test
        working-directory: r5
      # Install / cache dependencies with Cypress to handle caching Cypress binary.
      - uses: actions/setup-node@v2
        with:
          node-version: '12'        
      - uses: cypress-io/github-action@v3
        env:
          NEXT_PUBLIC_BASEMAP_DISABLED: true
          NEXT_PUBLIC_CYPRESS: true
          NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
        with:
          build: yarn build
          start: yarn start, yarn start-backend # runs frontend and java server together
          wait-on: 'http://localhost:3000, http://localhost:7070/version'
          wait-on-timeout: 60
          working-directory: ui
